# Generated by Django 4.2.4 on 2024-02-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=360)),
                ("second_decription", models.CharField(max_length=1000)),
                ("icon", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "About",
            },
        ),
    ]
