# Generated by Django 4.2.4 on 2024-02-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social_platform", models.CharField(max_length=50)),
                ("social_url", models.URLField(max_length=250)),
            ],
            options={
                "verbose_name": "Social Accounts",
                "verbose_name_plural": "Social Accounts",
            },
        ),
    ]
