# Generated by Django 4.2.4 on 2024-02-12 15:32

from django.db import migrations, models
import technologies.validators


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0002_socialaccounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=70)),
                (
                    "skill_icon",
                    models.FileField(
                        upload_to="icons",
                        validators=[technologies.validators.validate_file_extension],
                    ),
                ),
            ],
            options={
                "verbose_name": "المهارات",
                "verbose_name_plural": "مهاراتي",
            },
        ),
    ]
