# Generated by Django 4.2.4 on 2024-02-14 11:23

import about.models
from django.db import migrations, models
import technologies.validators


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0003_skills"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name": "About", "verbose_name_plural": "عــني"},
        ),
        migrations.AlterModelOptions(
            name="socialaccounts",
            options={
                "verbose_name": "Social Accounts",
                "verbose_name_plural": "حسابات التواصل",
            },
        ),
        migrations.RemoveField(
            model_name="about",
            name="icon",
        ),
        migrations.AddField(
            model_name="about",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=about.models.hero_picture_path,
                verbose_name="الصورة الشخصية",
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="description",
            field=models.CharField(max_length=360, verbose_name="العنوان تحت الرئيسي"),
        ),
        migrations.AlterField(
            model_name="about",
            name="second_decription",
            field=models.CharField(max_length=100, verbose_name="مقدمة تعريفية"),
        ),
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(max_length=50, verbose_name="العنوان الرئيسي"),
        ),
        migrations.AlterField(
            model_name="skills",
            name="skill_icon",
            field=models.FileField(
                upload_to="icons",
                validators=[technologies.validators.validate_file_extension],
                verbose_name="ايقونة المهارة svg",
            ),
        ),
        migrations.AlterField(
            model_name="skills",
            name="skill_name",
            field=models.CharField(max_length=70, verbose_name="اسم المهارة"),
        ),
        migrations.AlterField(
            model_name="socialaccounts",
            name="social_platform",
            field=models.CharField(max_length=50, verbose_name="نوع منصة التواصل"),
        ),
        migrations.AlterField(
            model_name="socialaccounts",
            name="social_url",
            field=models.URLField(
                max_length=250, verbose_name="رابط حسابك على هذه المنصة"
            ),
        ),
    ]
