# Generated by Django 4.2.4 on 2024-02-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0004_alter_about_options_alter_socialaccounts_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="second_decription",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="مقدمة تعريفية"
            ),
        ),
    ]
