# Generated by Django 4.2.4 on 2024-02-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_about_second_decription'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccounts',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='platform css in bootstrap'),
        ),
        migrations.AlterField(
            model_name='socialaccounts',
            name='social_platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع منصة التواصل'),
        ),
    ]
