# Generated by Django 4.2.4 on 2024-02-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(max_length=250),
        ),
    ]
