# Generated by Django 4.2.4 on 2024-02-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_remove_tag_created_at_remove_tag_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsgallery",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects-images", verbose_name="صور"
            ),
        ),
    ]
