# Generated by Django 4.2.4 on 2024-02-12 13:05

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_projectsgallery_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsgallery",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=projects.models.projects_picture_path,
                verbose_name="صور",
            ),
        ),
    ]
