# Generated by Django 4.2.4 on 2024-02-12 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_projectsgallery_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectsgallery",
            name="title",
        ),
    ]
