# Generated by Django 4.2.4 on 2024-02-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_remove_projectsgallery_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsgallery",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_images",
                to="projects.project",
            ),
        ),
    ]
