# Generated by Django 4.2.4 on 2024-02-14 14:52

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_projectsgallery_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=projects.models.projects_picture_path,
                verbose_name="الصورة الرئيسية للمشروع",
            ),
        ),
    ]
