# Generated by Django 4.2.4 on 2024-02-14 18:58

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_project_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=projects.models.mainImageProject_picture_path,
                verbose_name="الصورة الرئيسية للمشروع",
            ),
        ),
    ]
