# Generated by Django 4.2.4 on 2024-02-12 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="address",
            new_name="mobile",
        ),
    ]
