# Generated by Django 4.2.4 on 2024-02-12 12:08

from django.db import migrations, models
import experience.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=150)),
                ("description", models.CharField(max_length=300)),
                ("start_date", models.CharField(max_length=12)),
                ("end_date", models.CharField(max_length=12)),
                ("location", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=experience.models.experience_picture_path,
                        verbose_name="صور",
                    ),
                ),
            ],
        ),
    ]
