# Generated by Django 4.2.4 on 2024-02-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0002_experience_work_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="experience-images", verbose_name="صور"
            ),
        ),
    ]
