# Generated by Django 4.2.4 on 2024-02-12 13:05

from django.db import migrations, models
import experience.models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0003_alter_experience_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=experience.models.experience_picture_path,
                verbose_name="صور",
            ),
        ),
    ]
